export const LISTOFCITY = [
    {city : "Abidjan", country : "cote d'Ivorie", gmt:"+0:00", timechangehours : 0, timechangeminutes : +0}, 
    {city : "Accra", country : "Ghana", gmt:"+0:00",timechangehours : 0, timechangeminutes : +0}, 
    {city : "Addis Ababa", country : "Ethiopia", gmt:"+3:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Adelaide", country : "Australia", gmt:"+10:30", timechangehours : +10, timechangeminutes : +30},
    {city : "Bamako", country : "Africa", gmt: "+00:00", timechangehours : +0, timechangeminutes : +0},
    {city : "Cairo", country : "Egypt", gmt: "+02:00", timechangehours : +2, timechangeminutes : +0},
    {city : "Djibouti", country : "Somalia", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Harare", country : "Zimbabwe", gmt: "+02:00", timechangehours : +2, timechangeminutes : +0},
    {city : "Lagos", country : "Nigeria", gmt: "+01:00", timechangehours : +1, timechangeminutes : +0},
    {city : "Nairobi", country : "Kenya", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Tripoli", country : "libya", gmt: "+02:00", timechangehours : +2, timechangeminutes : +0},
    {city : "Buenos Aires", country : "Argentina", gmt: "-03:00", timechangehours : -3, timechangeminutes : +0},
    {city : "Rio Gallegos", country : "Argentina", gmt: "-03:00", timechangehours : -3, timechangeminutes : +0},
    {city : "Barbados", country : "west indies", gmt: "-04:00", timechangehours : -4, timechangeminutes : +0},
    {city : "Bogota", country : "Columbia", gmt: "-05:00", timechangehours : -5, timechangeminutes : +0},
    {city : "Chicago", country : "USA", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "Costa Rica", country : "Costa Rica", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "Denver", country : "Denver", gmt: "-07:00", timechangehours : -7, timechangeminutes : +0},
    {city : "El Salvador", country : "El Salvador", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "Guyana", country : "Guyana", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "Los Angeles", country : "USA", gmt: "-08:00", timechangehours : -8, timechangeminutes : +0},
    {city : "Mexico City", country : "Mexico", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "New York", country : "USA", gmt: "-05:00", timechangehours : -5, timechangeminutes : +0},
    {city : "Beulah", country : "USA", gmt: "-06:00", timechangehours : -6, timechangeminutes : +0},
    {city : "Port of Spain", country : "Trinidad and Tobago", gmt: "-04:00", timechangehours : -4, timechangeminutes : +0},
    {city : "Santiagoh", country : "Chile", gmt: "-03:00", timechangehours : -3, timechangeminutes : +0},
    {city : "Vancouver", country : "Canada", gmt: "-08:00", timechangehours : -8, timechangeminutes : +0},
    {city : "Toronto", country : "Canada", gmt: "-08:00", timechangehours : -8, timechangeminutes : +0},
    {city : "Baghdad", country : "Iraq", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Baku", country : "Azerbaijan", gmt: "+04:00", timechangehours : +4, timechangeminutes : +0},
    {city : "Bangkok", country : "Thailand", gmt: "+07:00", timechangehours : +7, timechangeminutes : +0},
    {city : "Beirut", country : "Lebanon", gmt: "+02:00", timechangehours : +2, timechangeminutes : +0},
    {city : "Brunei", country : "Brunei", gmt: "+08:00", timechangehours : +8, timechangeminutes : +0},
    {city : "Colombo", country : "Sri Lanka", gmt: "+05:30", timechangehours : +5, timechangeminutes : +30},
    {city : "Dhaka", country : "Bangladesh", gmt: "+06:00", timechangehours : +6, timechangeminutes : +0},
    {city : "Dubai", country : "UAE", gmt: "+04:00", timechangehours : +4, timechangeminutes : +0},
    {city : "Jakarta", country : "Indonesia", gmt: "+07:00", timechangehours : +7, timechangeminutes : +0},
    {city : "Karachi", country : "Pakistan", gmt: "+05:00", timechangehours : +5, timechangeminutes : +0},
    {city : "Kabul", country : "Afghanistan", gmt: "+04:30", timechangehours : +4, timechangeminutes : +30},
    {city : "Kathmandu", country : "Nepal", gmt: "+05:45", timechangehours : +5, timechangeminutes : +45},
    {city : "Kolkata", country : "India", gmt: "+05:30", timechangehours : +5, timechangeminutes : +30},
    {city : "Kuwait", country : "Kuwait", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Macau", country : "Macau", gmt: "+08:00", timechangehours : +8, timechangeminutes : +0},
    {city : "Riyadh", country : "Saudi Arabia", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Seoul", country : "South Korea", gmt: "+09:00", timechangehours : +9, timechangeminutes : +0},
    {city : "Singapore", country : "Singapore", gmt: "+08:00", timechangehours : +8, timechangeminutes : +0},
    {city : "Tokyo", country : "Japan", gmt: "+09:00", timechangehours : +9, timechangeminutes : +0},
    {city : "Sydney", country : "Australia", gmt: "+11:00", timechangehours : +11, timechangeminutes : +0},
    {city : "Berlin", country : "Germany", gmt: "+01:00", timechangehours : +1, timechangeminutes : +0},
    {city : "London", country : "England", gmt: "+00:00", timechangehours : +0, timechangeminutes : +0},
    {city : "Kyiv", country : "Ukraine", gmt: "+02:00", timechangehours : +2, timechangeminutes : +0},
    {city : "Moscow", country : "Russia", gmt: "+03:00", timechangehours : +3, timechangeminutes : +0},
    {city : "Rome", country : "Italy", gmt: "+01:00", timechangehours : +1, timechangeminutes : +0},     
    {city : "Colombo", country : "Sri Lanka", gmt: "+05:30", timechangehours : +5, timechangeminutes : +30}, 
    {city : "Brunei", country : "Brunei", gmt: "+08:00", timechangehours : +8, timechangeminutes : +0},  
]

